name: Unit_Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install GoogleTest
      run : |
          git clone https://github.com/google/googletest.git
          cd ./googletest/googletest/
          cmake -G "MinGW Makefiles" ..
          mingw32-make
          cd ../../ # go back to github repo directory

    - name: Compile & Link
      run: mingw32-make all_unit

    - name: Run Tests
      run: .\unit.exe --gtests_color=yes
